# Copyright 2015 Google Inc. All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# [START sonar_deployment]
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sonarqube
  namespace: build
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      nodeSelector:
        failure-domain.beta.kubernetes.io/zone: australia-southeast1-a
        failure-domain.beta.kubernetes.io/region: australia-southeast1
      containers:
      - name: sonarqube
        image: sonarqube:3.15.0
        ports:
        - containerPort: 9000
        readinessProbe:
          httpGet:
            path: /
            port: 9000
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 60
          successThreshold: 1
          failureThreshold: 5
        livenessProbe:
          httpGet:
            path: /
            port: 9000
          initialDelaySeconds: 120
          periodSeconds: 10
          timeoutSeconds: 60
          successThreshold: 1
          failureThreshold: 5
        volumeMounts:
        - mountPath: /sonar-data
          name: sonar-home
      volumes:
      - name: sonar-home
        gcePersistentDisk:
          pdName: sonar-home
          fsType: ext4
          partition: 1

# [END nexus_deployment]
