#!/bin/bash

function remove-lb () {

  echo "Now removing ingress service"
  kubectl --namespace=build get secret
  kubectl --namespace=build delete secret tls || true

  kubectl --namespace=build get ingress
  kubectl --namespace=build delete ingress build-ingress || true

  echo 'You should not see any ingress service'
  kubectl --namespace=build get ingress || true
}
